(() => {
'use strict';
const KEY='freedom_village_supabase_final_data';
const defaults={
 news:[],services:[],emergency:[],events:[],directory:[],requests:[],
 prayer:{fajr:'',sunrise:'',dhuhr:'',asr:'',maghrib:'',isha:'',imageData:''},
 settings:{village:'قرية الحرية',description:'منصة خدمية مركزية للأخبار والخدمات والمعلومات والشكاوى والاقتراحات.',hijriOffset:0}
};
const clone=o=>JSON.parse(JSON.stringify(o));
function loadData(){try{const x=JSON.parse(localStorage.getItem(KEY)||'{}');return {...clone(defaults),...x,settings:{...clone(defaults).settings,...(x.settings||{})},prayer:{...clone(defaults).prayer,...(x.prayer||{})}}}catch{return clone(defaults)}}
let data=loadData();
let session=null;
let section='home', adminTab='overview';
const app=document.getElementById('app');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,7);
async function save(){ localStorage.setItem(KEY,JSON.stringify(data)); if(session?.isAdmin){ try{ await FVCloud.saveData(data); }catch(e){ console.error(e); toast('تعذر مزامنة البيانات السحابية'); } } }
function toast(msg){const x=document.createElement('div');x.className='toast';x.textContent=msg;document.body.appendChild(x);setTimeout(()=>x.remove(),2600)}
function footer(){return '<div class="footer">منصة قرية الحرية — نظام خدمي سحابي</div>'}
function login(){const logo=localStorage.getItem('freedom_village_logo')||'./assets/logo.png';return `<main class="main login-page"><div class="hero center"><img class="logo login-logo" src="${esc(logo)}" onerror="this.onerror=null;this.src='./assets/logo.png';this.style.display='block'"><h2>منصة قرية الحرية</h2><p>${esc(data.settings.description)}</p></div><div class="card"><div class="form"><label class="password-wrap"><span>كلمة المرور</span><div class="password-line"><input class="input" id="password" type="password" autocomplete="current-password" placeholder="أدخل كلمة المرور"><button class="eye" id="togglePassword" type="button" aria-label="إظهار كلمة المرور">◉</button></div></label><button class="btn" id="login">دخول آمن</button></div><div class="notice">لا يحتاج الدخول إلى بريد إلكتروني. تتم مزامنة المنصة سحابياً عبر Supabase.</div></div>${footer()}</main>`}
function header(){const logo=localStorage.getItem('freedom_village_logo')||'./assets/logo.png';return `<header class="top"><div class="brand"><img class="logo" src="${esc(logo)}" onerror="this.onerror=null;this.src='./assets/logo.png'"><div><h1>منصة قرية الحرية</h1><p>الخدمات والمعلومات لأهل القرية</p></div><div class="status">● ${navigator.onLine?'متصل':'غير متصل'}</div></div></header>`}
function toArabicDigits(v){return String(v).replace(/\d/g,d=>'٠١٢٣٤٥٦٧٨٩'[d])}
function hijriParts(date){
  try{
    const fmt=new Intl.DateTimeFormat('ar-SA-u-ca-islamic-umalqura',{day:'numeric',month:'long',year:'numeric',weekday:'long'});
    const parts=Object.fromEntries(fmt.formatToParts(date).filter(x=>x.type!=='literal').map(x=>[x.type,x.value]));
    return {day:parts.day,month:parts.month,year:parts.year,weekday:parts.weekday};
  }catch{return null}
}
function getClock(){
  const d=new Date();
  return new Intl.DateTimeFormat('ar-SA',{hour:'numeric',minute:'2-digit',second:'2-digit',hour12:true}).format(d);
}
function getGregorian(){return new Intl.DateTimeFormat('ar-SA',{dateStyle:'full'}).format(new Date())}
function getHijriLabel(){
  const d=new Date();
  const offset=Number(data.settings?.hijriOffset||0);
  d.setDate(d.getDate()+offset);
  const h=hijriParts(d);
  if(!h)return 'تعذر حساب التاريخ الهجري';
  return `${toArabicDigits(h.weekday)}، ${toArabicDigits(h.day)} ${h.month} ${toArabicDigits(h.year)} هـ`;
}
function dates(){return `<div class="date"><span class="pill">📅 ${esc(getGregorian())}</span><span class="pill">🌙 ${esc(getHijriLabel())}</span><span class="pill">🕒 <b id="liveClock">${esc(getClock())}</b></span></div>`}
const navItems=[['home','⌂','الرئيسية'],['news','▣','الأخبار'],['prayer','◷','الصلاة'],['services','✦','الخدمات'],['requests','✎','الطلبات']];
function nav(){return `<nav class="bottom">${navItems.map(([id,ic,t])=>`<button class="nav ${section===id?'active':''}" data-nav="${id}"><span>${ic}</span><small>${t}</small></button>`).join('')}</nav>`}
function home(){const tiles=[['news','📰','الأخبار','المستجدات والإعلانات'],['prayer','🕌','مواقيت الصلاة','المواعيد اليومية'],['services','🧰','الخدمات','خدمات القرية'],['requests','📝','شكوى / اقتراح','إرسال ومتابعة الطلب'],['emergency','🚨','الطوارئ','أرقام التواصل السريع'],['events','📅','الفعاليات','المناسبات والأنشطة'],['directory','📍','دليل القرية','الأسماء والخدمات'],['about','ℹ️','عن المنصة','التعريف والتواصل']];if(session?.isAdmin)tiles.push(['admin','⚙️','الإدارة','للمشرفين']);return `<section class="section active"><div class="hero"><h2>مرحباً بكم في ${esc(data.settings.village)}</h2><p>${esc(data.settings.description)}</p>${dates()}</div><div class="grid">${tiles.map(([id,i,t,d])=>`<button class="card tile" data-nav="${id}"><span class="icon">${i}</span><b>${t}</b><small>${d}</small></button>`).join('')}</div>${footer()}</section>`}
function list(id,title,arr){return `<section class="section active"><div class="section-head"><h2>${title}</h2><button class="btn alt" data-nav="home">الرئيسية</button></div><div class="list">${arr.length?arr.map(x=>`<article class="item"><h3>${esc(x.title)}</h3><p>${esc(x.body)}</p>${x.date?`<small>${esc(x.date)}</small>`:''}</article>`).join(''):'<div class="notice">لا توجد بيانات منشورة حالياً.</div>'}</div></section>`}
function prayer(){const p=data.prayer||{};const n=[['fajr','الفجر'],['sunrise','الشروق'],['dhuhr','الظهر'],['asr','العصر'],['maghrib','المغرب'],['isha','العشاء']];return `<section class="section active"><div class="section-head"><h2>مواقيت الصلاة</h2><button class="btn alt" data-nav="home">الرئيسية</button></div><div class="card">${(p.image_url||p.imageData)?`<img src="${p.image_url||p.imageData}" class="prayer-img" alt="مواقيت الصلاة">`:''}<div class="grid prayer-grid">${n.map(([k,t])=>`<div class="item center"><b>${t}</b><h3>${esc(p[k]||'—')}</h3></div>`).join('')}</div><p class="center muted">المواقيت محفوظة سحابياً ومتزامنة بين الأجهزة.</p></div></section>`}
function requests(){return `<section class="section active"><div class="section-head"><h2>الشكاوى والاقتراحات</h2><button class="btn alt" data-nav="home">الرئيسية</button></div><div class="card"><div class="form"><select id="rtype"><option value="complaint">شكوى</option><option value="suggestion">اقتراح</option></select><input class="input" id="rname" placeholder="الاسم"><input class="input" id="rphone" inputmode="tel" placeholder="رقم الهاتف"><textarea id="rbody" rows="6" placeholder="اكتب التفاصيل"></textarea><button class="btn" id="send">إرسال الطلب</button></div></div><div class="card"><div class="form"><input class="input" id="track" placeholder="رقم المتابعة"><button class="btn alt" id="trackBtn">متابعة الطلب</button><div id="trackResult"></div></div></div></section>`}
function admin(){if(!session?.isAdmin)return `<section class="section active"><div class="section-head"><h2>غير مصرح</h2><button class="btn alt" data-nav="home">الرئيسية</button></div><div class="card"><div class="notice">هذه الصفحة مخصصة للمشرفين فقط.</div></div></section>`;return `<section class="section active"><div class="adminHead"><div><b>لوحة الإدارة — ${esc(session.name)}</b><p>إدارة المنصة والبيانات سحابياً عبر Supabase</p></div><button class="btn danger" id="logout">تسجيل الخروج</button></div><div class="tabs">${[['overview','الرئيسية'],['news','الأخبار'],['prayer','الصلاة'],['requests','الطلبات'],['content','المحتوى'],['security','الأمان'],['settings','الإعدادات']].map(([k,t])=>`<button class="${adminTab===k?'active':''}" data-at="${k}">${t}</button>`).join('')}</div>${adminTabView()}</section>`}
function adminTabView(){const d=data,t=adminTab;
 if(t==='overview')return `<div class="grid"><div class="card"><b>الأخبار</b><h2>${d.news.length}</h2></div><div class="card"><b>الطلبات</b><h2>${d.requests.length}</h2></div><div class="card"><b>الخدمات</b><h2>${d.services.length}</h2></div></div>`;
 if(t==='news')return `<div class="card"><div class="form"><input class="input" id="nt" placeholder="عنوان الخبر"><textarea id="nb" rows="5" placeholder="نص الخبر"></textarea><button class="btn" id="addNews">نشر الخبر</button></div></div><div class="list">${d.news.map(x=>`<article class="item"><h3>${esc(x.title)}</h3><p>${esc(x.body)}</p><button class="btn danger" data-del="news" data-id="${x.id}">حذف</button></article>`).join('')}</div>`;
 if(t==='prayer'){const p=d.prayer;return `<div class="card"><div class="form">${[['fajr','الفجر'],['sunrise','الشروق'],['dhuhr','الظهر'],['asr','العصر'],['maghrib','المغرب'],['isha','العشاء']].map(([k,l])=>`<input class="input" id="p_${k}" value="${esc(p[k]||'')}" placeholder="${l}">`).join('')}<label class="file-label">صورة مواقيت الصلاة (اختياري)<input type="file" id="p_img" accept="image/*"></label>${(p.image_url||p.imageData)?'<button class="btn danger" id="removePrayerImg">حذف صورة المواقيت</button>':''}<button class="btn" id="savePrayer">حفظ المواقيت</button></div></div>`}
 if(t==='requests')return `<div class="list">${d.requests.length?d.requests.map(r=>`<article class="item"><h3>${r.type==='complaint'?'شكوى':'اقتراح'} — ${esc(r.tracking)}</h3><p><b>الاسم:</b> ${esc(r.name||'—')} ${r.phone?`<br><b>الهاتف:</b> ${esc(r.phone)}`:''}</p><p>${esc(r.body)}</p><p>الحالة: <b>${esc(r.statusLabel)}</b></p><div class="row">${[['under_review','قيد المراجعة'],['processing','قيد المعالجة'],['resolved','تم الحل'],['closed','مغلق']].map(([s,l])=>`<button class="btn" data-status="${s}" data-id="${r.id}">${l}</button>`).join('')}<button class="btn danger" data-del="requests" data-id="${r.id}">حذف</button></div></article>`).join(''):'<div class="notice">لا توجد طلبات.</div>'}</div>`;
 if(t==='content')return `<div class="card"><div class="form"><select id="ctype"><option value="services">خدمة</option><option value="emergency">طوارئ</option><option value="events">فعالية</option><option value="directory">دليل القرية</option></select><input class="input" id="ct" placeholder="العنوان"><textarea id="cb" rows="4" placeholder="التفاصيل"></textarea><input class="input" id="cd" placeholder="التاريخ (اختياري)"><button class="btn" id="addContent">إضافة</button></div></div><div class="list">${['services','emergency','events','directory'].flatMap(k=>d[k].map(x=>({...x,kind:k}))).map(x=>`<article class="item"><small>${x.kind}</small><h3>${esc(x.title)}</h3><p>${esc(x.body)}</p>${x.date?`<small>${esc(x.date)}</small>`:''}<br><button class="btn danger" data-del="${x.kind}" data-id="${x.id}">حذف</button></article>`).join('')}</div>`;
 if(t==='security')return `<div class="grid"><div class="card"><b>الحالة</b><p>الدخول بكلمة مرور فقط، مع جلسة Supabase مجهولة ومحمية.</p></div><div class="card"><b>الصلاحية</b><p>${session?.isAdmin?'مشرف — يمكنه إدارة المحتوى':'مستخدم'}</p></div><div class="card"><b>المزامنة</b><p>${navigator.onLine?'متصلة':'غير متصلة'}</p></div></div><div class="card"><div class="notice">كلمات المرور لا تُحفظ داخل GitHub كنص صريح. يتم التحقق منها عبر Edge Function في Supabase.</div></div>`;
 return `<div class="card"><div class="form"><input class="input" id="svillage" value="${esc(d.settings.village)}" placeholder="اسم القرية"><textarea id="sdesc" rows="4" placeholder="وصف المنصة">${esc(d.settings.description)}</textarea><label>تصحيح التاريخ الهجري (بالأيام)<input class="input" id="hijriOffset" type="number" step="1" value="${Number(d.settings.hijriOffset||0)}"><small class="muted">٠ = التاريخ التلقائي لأم القرى، ويمكن وضع +١ أو -١ عند الحاجة.</small></label><label class="file-label">شعار/صورة المنصة<input type="file" id="appLogo" accept="image/*"></label><div class="row"><button class="btn" id="saveSettings">حفظ الإعدادات</button><button class="btn alt" id="backup">إنشاء نسخة احتياطية</button><label class="file-label compact">استيراد نسخة<input type="file" id="restore" accept="application/json"></label></div><button class="btn danger" id="reset">حذف جميع بيانات المنصة وإعادة الضبط</button></div></div>`;
}
function render(){if(!session){app.innerHTML=login();bind();return}let content;if(section==='home')content=home();else if(section==='news')content=list('news','الأخبار',data.news);else if(section==='prayer')content=prayer();else if(section==='services')content=list('services','الخدمات',data.services);else if(section==='emergency')content=list('emergency','الطوارئ',data.emergency);else if(section==='events')content=list('events','الفعاليات',data.events);else if(section==='directory')content=list('directory','دليل القرية',data.directory);else if(section==='about')content=list('about','عن المنصة',[{title:data.settings.village,body:data.settings.description}]);else if(section==='requests')content=requests();else content=admin();app.innerHTML=`<div class="app">${header()}<main class="main">${content}</main>${nav()}</div>`;const logo=localStorage.getItem('freedom_village_logo');if(logo)applyLogo(logo);bind();startClock()}
function bind(){document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>{section=b.dataset.nav;render()});document.querySelectorAll('[data-at]').forEach(b=>b.onclick=()=>{adminTab=b.dataset.at;render()});
 const loginBtn=document.getElementById('login');if(loginBtn)loginBtn.onclick=async()=>{const password=document.getElementById('password').value;if(!password)return toast('أدخل كلمة المرور');loginBtn.disabled=true;try{let {data:sd}=await FVCloud.auth.getSession();if(!sd.session){const r=await FVCloud.auth.signInAnonymously();if(r.error)throw r.error;}const result=await FVCloud.authorize(password);if(!result.ok)throw new Error(result.error||'كلمة المرور غير صحيحة');await FVCloud.auth.refreshSession();}catch(e){console.error(e);toast(e.message||'كلمة المرور غير صحيحة')}finally{loginBtn.disabled=false}};const tp=document.getElementById('togglePassword');if(tp)tp.onclick=()=>{const i=document.getElementById('password');if(i){i.type=i.type==='password'?'text':'password';tp.textContent=i.type==='password'?'◉':'◎'}};
 const lo=document.getElementById('logout');if(lo)lo.onclick=async()=>{lo.disabled=true;const r=await FVCloud.logoutAccess();if(!r.ok)toast(r.error||'تعذر تسجيل الخروج');lo.disabled=false};
 const send=document.getElementById('send');if(send)send.onclick=async()=>{const body=document.getElementById('rbody').value.trim();if(!body)return toast('اكتب تفاصيل الطلب');const tracking='FV-'+new Date().getFullYear()+'-'+Math.random().toString(36).slice(2,8).toUpperCase();const userId=(await FVCloud.auth.getUser()).data.user?.id;const row={id:uid(),tracking,type:document.getElementById('rtype').value,name:document.getElementById('rname').value.trim(),phone:document.getElementById('rphone').value.trim(),body,status:'under_review',statusLabel:'قيد المراجعة',createdAt:new Date().toISOString(),userId};data.requests.unshift(row);const {error}=await FVCloud.client.from('requests').insert({id:row.id,tracking:row.tracking,type:row.type,name:row.name,phone:row.phone,body:row.body,status:row.status,status_label:row.statusLabel,user_id:userId});if(error){console.error(error);return toast('تعذر إرسال الطلب إلى الخادم')}localStorage.setItem(KEY,JSON.stringify(data));toast('تم إرسال الطلب. رقم المتابعة: '+tracking);document.getElementById('rbody').value='';};
 const tr=document.getElementById('trackBtn');if(tr)tr.onclick=()=>{const r=data.requests.find(x=>x.tracking.toUpperCase()===document.getElementById('track').value.trim().toUpperCase());document.getElementById('trackResult').innerHTML=r?`<div class="notice">رقم الطلب: <b>${esc(r.tracking)}</b><br>الحالة: <b>${esc(r.statusLabel)}</b></div>`:'<div class="notice">لم يتم العثور على الطلب.</div>'};
 const an=document.getElementById('addNews');if(an)an.onclick=async()=>{const title=document.getElementById('nt').value.trim(),body=document.getElementById('nb').value.trim();if(!title||!body)return toast('أدخل عنوان الخبر والنص');const row={id:uid(),title,body,date:new Date().toLocaleDateString('ar-SY')};an.disabled=true;try{await FVCloud.upsertContent(row,'news');data.news.unshift(row);localStorage.setItem(KEY,JSON.stringify(data));render();toast('تم نشر الخبر سحابياً')}catch(e){console.error(e);toast('تعذر نشر الخبر')}finally{an.disabled=false}};
 const sp=document.getElementById('savePrayer');if(sp)sp.onclick=async()=>{for(const k of ['fajr','sunrise','dhuhr','asr','maghrib','isha'])data.prayer[k]=document.getElementById('p_'+k).value.trim();const f=document.getElementById('p_img');if(f.files[0]){try{data.prayer.image_url=await FVCloud.uploadImage(f.files[0],'prayer/times');await save();render();toast('تم حفظ المواقيت والصورة سحابياً')}catch(e){console.error(e);toast('تعذر رفع الصورة')}}else{await save();render();toast('تم حفظ المواقيت')}};
 const rip=document.getElementById('removePrayerImg');if(rip)rip.onclick=async()=>{data.prayer.image_url='';data.prayer.imageData='';await save();render()};
 const ac=document.getElementById('addContent');if(ac)ac.onclick=async()=>{const k=document.getElementById('ctype').value,title=document.getElementById('ct').value.trim(),body=document.getElementById('cb').value.trim(),date=document.getElementById('cd').value.trim();if(!title||!body)return toast('أدخل العنوان والتفاصيل');const row={id:uid(),title,body,date};ac.disabled=true;try{await FVCloud.upsertContent(row,k);data[k].unshift(row);localStorage.setItem(KEY,JSON.stringify(data));render();toast('تمت الإضافة سحابياً')}catch(e){console.error(e);toast('تعذر حفظ العنصر')}finally{ac.disabled=false}};
 document.querySelectorAll('[data-status]').forEach(b=>b.onclick=async()=>{const r=data.requests.find(x=>x.id===b.dataset.id);const map={under_review:'قيد المراجعة',processing:'قيد المعالجة',resolved:'تم الحل',closed:'مغلق'};if(r){const status=b.dataset.status,statusLabel=map[status];try{await FVCloud.updateRequest(r.id,{status,statusLabel});r.status=status;r.statusLabel=statusLabel;localStorage.setItem(KEY,JSON.stringify(data));render();toast('تم تحديث حالة الطلب')}catch(e){console.error(e);toast('تعذر تحديث الطلب')}}});
 document.querySelectorAll('[data-del]').forEach(b=>b.onclick=async()=>{if(!confirm('هل تريد حذف هذا العنصر؟'))return;const k=b.dataset.del,id=b.dataset.id;try{if(k==='requests')await FVCloud.deleteRequest(id);else await FVCloud.deleteContent(id);data[k]=data[k].filter(x=>x.id!==id);localStorage.setItem(KEY,JSON.stringify(data));render();toast('تم الحذف نهائياً من السحابة')}catch(e){console.error(e);toast('تعذر الحذف')}});
 const ss=document.getElementById('saveSettings');if(ss)ss.onclick=async()=>{data.settings.village=document.getElementById('svillage').value.trim()||'قرية الحرية';data.settings.description=document.getElementById('sdesc').value.trim();data.settings.hijriOffset=Number(document.getElementById('hijriOffset')?.value||0);const f=document.getElementById('appLogo');if(f.files[0]){try{data.settings.logoUrl=await FVCloud.uploadImage(f.files[0],'branding/logo');localStorage.setItem('freedom_village_logo',data.settings.logoUrl);applyLogo(data.settings.logoUrl);await save();render();toast('تم حفظ الإعدادات والشعار سحابياً')}catch(e){console.error(e);toast('تعذر رفع الشعار')}}else{await save();render();toast('تم حفظ الإعدادات')}};
 const backup=document.getElementById('backup');if(backup)backup.onclick=()=>{const payload={app:'منصة قرية الحرية',version:'4.0',exportedAt:new Date().toISOString(),data,logo:localStorage.getItem('freedom_village_logo')||null};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='نسخة-احتياطية-منصة-قرية-الحرية-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
 const restore=document.getElementById('restore');if(restore)restore.onchange=()=>{const f=restore.files[0];if(!f)return;const rd=new FileReader();rd.onload=async()=>{try{const p=JSON.parse(rd.result);if(!p.data||!p.data.settings)throw Error();if(!confirm('سيتم استيراد النسخة إلى السحابة الحالية وإضافة/تحديث بياناتها. هل تريد المتابعة؟'))return;restore.disabled=true;await FVCloud.restoreData(p.data);data=await FVCloud.loadData(clone(defaults));localStorage.setItem(KEY,JSON.stringify(data));if(p.logo)localStorage.setItem('freedom_village_logo',p.logo);render();toast('تمت استعادة النسخة الاحتياطية إلى السحابة بنجاح')}catch(e){console.error(e);toast('ملف النسخة الاحتياطية غير صالح أو تعذر استيراده')}finally{restore.disabled=false;restore.value=''}};rd.readAsText(f)};
 const reset=document.getElementById('reset');if(reset)reset.onclick=async()=>{if(!confirm('سيتم حذف المحتوى والطلبات والمواقيت والإعدادات من السحابة لجميع المستخدمين. هذا الإجراء نهائي. هل أنت متأكد؟'))return;reset.disabled=true;try{await FVCloud.resetCloud();data=clone(defaults);localStorage.setItem(KEY,JSON.stringify(data));localStorage.removeItem('freedom_village_logo');render();toast('تمت إعادة ضبط بيانات المنصة سحابياً')}catch(e){console.error(e);toast('تعذر إعادة الضبط السحابي')}finally{reset.disabled=false}};
}
let clockTimer=null;
function startClock(){clearInterval(clockTimer);const el=document.getElementById('liveClock');if(!el)return;const tick=()=>{el.textContent=getClock()};tick();clockTimer=setInterval(tick,1000)}
function applyLogo(src){document.querySelectorAll('.logo').forEach(i=>i.src=src)}
async function hydrate(){try{data=await FVCloud.loadData(data);localStorage.setItem(KEY,JSON.stringify(data));if(data.settings.logoUrl){localStorage.setItem('freedom_village_logo',data.settings.logoUrl);applyLogo(data.settings.logoUrl);}}catch(e){console.error(e);toast('تعذر تحميل بيانات المنصة السحابية');}}
async function handleAuth(authSession){
  if(!authSession){session=null;section='home';render();return;}
  try{
    const user=authSession.user;
    const meta=user?.app_metadata||{};
    if(!meta.access_granted){session=null;section='home';render();return;}
    session={id:user.id,name:meta.is_admin?'المشرف':'مستخدم المنصة',isAdmin:meta.is_admin===true,active:true};
    await hydrate(); section='home'; render(); subscribeRealtime();
  }catch(e){console.error(e);toast('تعذر تهيئة الجلسة السحابية');await FVCloud.auth.signOut();}
}
async function boot(){
  const {data:{session:s}}=await FVCloud.auth.getSession();
  if(s) await handleAuth(s); else render();
  FVCloud.auth.onAuthStateChange((_event,sess)=>{setTimeout(()=>handleAuth(sess),0);});
}
let realtimeChannels=[];function subscribeRealtime(){if(realtimeChannels.length)return;for(const table of ['content_items','requests','profiles','prayer_times','app_settings']){const ch=FVCloud.client.channel('fv-'+table).on('postgres_changes',{event:'*',schema:'public',table},async()=>{if(!session)return;try{await hydrate();render();}catch(e){console.error(e)}}).subscribe();realtimeChannels.push(ch);}}
window.addEventListener('online',()=>render());window.addEventListener('offline',()=>render());
boot();
})();
